/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.Month;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author User
 */
public class Dash extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Dashboard
     */
    int[] l_month = new int[]{31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};

    public Dash() {
        initComponents();
        table_update();
        lineCreate();
        try {
            notifi();
        } catch (ParseException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        pnChart.setLayout(new java.awt.BorderLayout());
    }

    public void notifi() throws ParseException {
        DefaultListModel mod = new DefaultListModel();
        jList1.setModel(mod);

        Object[][] data = jtable2_noti();

        int row = dashboard.getRowCount();

        for (int i = 0; i < row; i++) {
            if (data[i][4].toString().equals("-")) {

            } else {
                
                SimpleDateFormat formatter = new SimpleDateFormat("dd-MM", Locale.ENGLISH);
                String timeString = formatter.format(new Date());

                
                String return_day = data[i][4].toString();
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM", Locale.ENGLISH);
                Date firstDate = sdf.parse(return_day);
                Date secondDate = sdf.parse(timeString);
                
                

                long day_diff = (secondDate.getTime() - firstDate.getTime())/(1000*60*60*24);
                //long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
                
                //ติดลบ เกินไปเเล้วกี่วัน
                if(day_diff < 0){
                    System.out.println("เลยไปเเล้ว "+Math.abs(day_diff));
                    mod.addElement("รถหมายเลข "+data[i][1].toString().substring(8)+"จะคืนอีกภายใน "+Math.abs(day_diff)+" วัน ในวันที่"+return_day);
                }else if(day_diff < 30){
                    //ถึงวันคืนอีกในวันที่
                    System.out.println("จะคืนอีกภายใน "+Math.abs(day_diff));
                    mod.addElement("รถหมายเลข "+data[i][1].toString().substring(8)+" เลยเวลาคืนไปเเล้ว"+Math.abs(day_diff)+" วัน ตั้งเเต่วันที่ "+return_day);
                    
                }

                

            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        pnChart1 = new javax.swing.JPanel();
        btn3DPie1 = new javax.swing.JButton();
        btnLineChart1 = new javax.swing.JButton();
        btnBarChart1 = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        jLabel_available = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mb_reg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        maintainance = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rent = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Summary = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        summary_tab = new javax.swing.JPanel();
        user_panel = new javax.swing.JPanel();
        top_plane = new javax.swing.JPanel();
        status_panel = new javax.swing.JPanel();
        available_p = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_a = new javax.swing.JLabel();
        busy_p = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_b = new javax.swing.JLabel();
        Wait = new javax.swing.JPanel();
        jLabel_c = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dashcalender = new com.toedter.calendar.JCalendar();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel13 = new javax.swing.JPanel();
        detail_panel = new javax.swing.JPanel();
        table_panel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dashboard = new javax.swing.JTable()
        {
            @Override

            public Component prepareRenderer (TableCellRenderer renderer, int rowIndex, int columnIndex){
                Component componenet = super.prepareRenderer(renderer, rowIndex, columnIndex);

                Object value = getModel().getValueAt(rowIndex,columnIndex);

                if(columnIndex == 5){

                    if(value.equals("ว่าง"))
                    {

                        componenet.setBackground(Color.GREEN);
                        componenet.setForeground(Color.BLACK);

                    }
                    if(value.equals("ไม่ว่าง")){
                        // if date  equal current date
                        componenet.setBackground(Color.RED);
                        componenet.setForeground(Color.BLACK);
                    }

                }

                else {

                    componenet.setBackground(Color.WHITE);
                    componenet.setForeground(Color.BLACK);
                }

                return componenet;
            }

        }
        ;
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dashboard2 = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        dashboard3 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        select_month = new javax.swing.JComboBox<>();
        select_year = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        available_p2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jPanel7 = new javax.swing.JPanel();
        available_p4 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        available_p3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        available_p1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        pnChart = new javax.swing.JPanel();
        btn3DPie = new javax.swing.JButton();
        btnLineChart = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        pnChart1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnChart1Layout = new javax.swing.GroupLayout(pnChart1);
        pnChart1.setLayout(pnChart1Layout);
        pnChart1Layout.setHorizontalGroup(
            pnChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnChart1Layout.setVerticalGroup(
            pnChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        btn3DPie1.setText("3D Pie Chart");
        btn3DPie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3DPie1ActionPerformed(evt);
            }
        });

        btnLineChart1.setText("Line Chart");
        btnLineChart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineChart1ActionPerformed(evt);
            }
        });

        btnBarChart1.setText("Bar Chart");
        btnBarChart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarChart1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnChart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                            .addGap(0, 891, Short.MAX_VALUE)
                            .addComponent(btn3DPie1)
                            .addGap(18, 18, 18)
                            .addComponent(btnBarChart1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnLineChart1)))
                    .addContainerGap()))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnChart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLineChart1)
                        .addComponent(btnBarChart1)
                        .addComponent(btn3DPie1))
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(204, 204, 204));

        jLabel_available.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_available.setFocusTraversalPolicyProvider(true);

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Summary");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mb_reg.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("Registeration");

        javax.swing.GroupLayout mb_regLayout = new javax.swing.GroupLayout(mb_reg);
        mb_reg.setLayout(mb_regLayout);
        mb_regLayout.setHorizontalGroup(
            mb_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mb_regLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mb_regLayout.setVerticalGroup(
            mb_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mb_regLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(mb_regLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        maintainance.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Maintainace");

        javax.swing.GroupLayout maintainanceLayout = new javax.swing.GroupLayout(maintainance);
        maintainance.setLayout(maintainanceLayout);
        maintainanceLayout.setHorizontalGroup(
            maintainanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintainanceLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintainanceLayout.setVerticalGroup(
            maintainanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintainanceLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(maintainanceLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rent.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Rent Transaction");

        javax.swing.GroupLayout rentLayout = new javax.swing.GroupLayout(rent);
        rent.setLayout(rentLayout);
        rentLayout.setHorizontalGroup(
            rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rentLayout.setVerticalGroup(
            rentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("RentalMB ");

        javax.swing.GroupLayout jLabel_availableLayout = new javax.swing.GroupLayout(jLabel_available);
        jLabel_available.setLayout(jLabel_availableLayout);
        jLabel_availableLayout.setHorizontalGroup(
            jLabel_availableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(maintainance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mb_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLabel_availableLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jLabel_availableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(36, 36, 36))
        );
        jLabel_availableLayout.setVerticalGroup(
            jLabel_availableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLabel_availableLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(93, 93, 93)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mb_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(maintainance, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Summary.setBackground(new java.awt.Color(204, 204, 204));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        summary_tab.setLayout(new java.awt.GridLayout(2, 1));

        user_panel.setLayout(new java.awt.GridLayout(1, 3));

        status_panel.setLayout(new java.awt.GridLayout(1, 0));

        available_p.setBackground(new java.awt.Color(204, 255, 204));
        available_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                available_pMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setText("Available");

        jLabel_a.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel_a.setText("0");

        javax.swing.GroupLayout available_pLayout = new javax.swing.GroupLayout(available_p);
        available_p.setLayout(available_pLayout);
        available_pLayout.setHorizontalGroup(
            available_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_pLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, available_pLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_a)
                .addContainerGap())
        );
        available_pLayout.setVerticalGroup(
            available_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_pLayout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel_a))
        );

        status_panel.add(available_p);

        busy_p.setBackground(new java.awt.Color(255, 153, 153));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("Busy");

        jLabel_b.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel_b.setText("0");

        javax.swing.GroupLayout busy_pLayout = new javax.swing.GroupLayout(busy_p);
        busy_p.setLayout(busy_pLayout);
        busy_pLayout.setHorizontalGroup(
            busy_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busy_pLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, busy_pLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_b)
                .addGap(51, 51, 51))
        );
        busy_pLayout.setVerticalGroup(
            busy_pLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busy_pLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel_b))
        );

        status_panel.add(busy_p);

        Wait.setBackground(new java.awt.Color(255, 255, 0));

        jLabel_c.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel_c.setText("0");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 0));
        jLabel11.setText("Check");

        javax.swing.GroupLayout WaitLayout = new javax.swing.GroupLayout(Wait);
        Wait.setLayout(WaitLayout);
        WaitLayout.setHorizontalGroup(
            WaitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WaitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_c)
                .addGap(51, 51, 51))
        );
        WaitLayout.setVerticalGroup(
            WaitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel_c))
        );

        status_panel.add(Wait);

        jPanel12.setMinimumSize(new java.awt.Dimension(150, 114));
        jPanel12.setLayout(new java.awt.GridLayout(2, 1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Summary");
        jPanel12.add(jLabel7);

        jLabel5.setForeground(new java.awt.Color(153, 153, 255));
        jLabel5.setText("welcome back mr.sahussawud");
        jPanel12.add(jLabel5);

        javax.swing.GroupLayout top_planeLayout = new javax.swing.GroupLayout(top_plane);
        top_plane.setLayout(top_planeLayout);
        top_planeLayout.setHorizontalGroup(
            top_planeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_planeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(756, 756, 756))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_planeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashcalender, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        top_planeLayout.setVerticalGroup(
            top_planeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(top_planeLayout.createSequentialGroup()
                .addGroup(top_planeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(top_planeLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, top_planeLayout.createSequentialGroup()
                        .addContainerGap(93, Short.MAX_VALUE)
                        .addComponent(dashcalender, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(status_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        user_panel.add(top_plane);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Clock");

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jList1.setFont(new java.awt.Font("Angsana New", 2, 24)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 522, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        user_panel.add(jPanel11);

        summary_tab.add(user_panel);

        jPanel13.setLayout(new java.awt.BorderLayout());

        detail_panel.setLayout(new java.awt.BorderLayout());

        table_panel.setLayout(new java.awt.BorderLayout(30, 30));

        dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1001", "yamaha nouvo 125 2กช 8256 ", "Available", null, null, null, "ืืีืีเช็คเมื่อ 21/07/63"},
                {"2001", "honda zoomer-x 125 ", "ฺBusy", null, null, null, "return 20/02/63"},
                {"2002", "honda 25หกก", "Maintainance", null, null, null, "น้ำมันเครื่อง"},
                {"2001", "honda กช2513", "Available", null, null, null, "เช็คเมื่อ 20/05/62"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "รหัสรถ", "ยี่ห้อ", "รุ่น", "สี", "ป้ายทะเบียน", "สถานะ", "วันที่ลงทะเบียน"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        dashboard.setToolTipText("");
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboard.setName(""); // NOI18N
        jScrollPane1.setViewportView(dashboard);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(1373, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("จักรยานยนต์ทั้งหมด", jPanel9);

        dashboard2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "วันที่", "รายการ", "ประเภท", "ราคา", "วันคืนรถ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(dashboard2);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("ธุรกรรมล่าสุด", jPanel10);

        dashboard3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "เลขที่รถ", "ยี่ห้อ", "ทะเบียน", "ปัญหา", "รายละเอียด", "วันที่ซ่อม", "วันสิ้นสุด พรบ."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(dashboard3);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1251, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jTabbedPane2.addTab("รายการตรวจสอบ", jPanel14);

        table_panel.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        detail_panel.add(table_panel, java.awt.BorderLayout.CENTER);

        jPanel13.add(detail_panel, java.awt.BorderLayout.PAGE_START);

        summary_tab.add(jPanel13);

        jTabbedPane1.addTab("Summary", summary_tab);

        jLabel16.setFont(new java.awt.Font("Leelawadee UI", 2, 36)); // NOI18N
        jLabel16.setText("Dashboard ");

        select_month.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        select_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01January", "02February", "03March", "04April", "05May", "06June", "07July", "08August", "09September", "10October", "11November", "12December" }));
        select_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_monthActionPerformed(evt);
            }
        });

        select_year.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        select_year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        select_year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_yearActionPerformed(evt);
            }
        });

        jPanel15.setLayout(new java.awt.GridLayout(1, 3));

        available_p2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("จำนวนรายการ");

        label3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        label3.setText("0");

        javax.swing.GroupLayout available_p2Layout = new javax.swing.GroupLayout(available_p2);
        available_p2.setLayout(available_p2Layout);
        available_p2Layout.setHorizontalGroup(
            available_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, available_p2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        available_p2Layout.setVerticalGroup(
            available_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p2Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        available_p4.setBackground(new java.awt.Color(255, 153, 153));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("รายจ่าย");

        label6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        label6.setText("0");

        javax.swing.GroupLayout available_p4Layout = new javax.swing.GroupLayout(available_p4);
        available_p4.setLayout(available_p4Layout);
        available_p4Layout.setHorizontalGroup(
            available_p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p4Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, available_p4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        available_p4Layout.setVerticalGroup(
            available_p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p4Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(40, 40, 40)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(available_p4);

        available_p3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 153, 0));
        jLabel19.setText("รายรับ");

        label4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        label4.setText("0");

        javax.swing.GroupLayout available_p3Layout = new javax.swing.GroupLayout(available_p3);
        available_p3.setLayout(available_p3Layout);
        available_p3Layout.setHorizontalGroup(
            available_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p3Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(available_p3Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        available_p3Layout.setVerticalGroup(
            available_p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p3Layout.createSequentialGroup()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(available_p3);

        available_p1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 0));
        jLabel17.setText("ยอดขายทั้งหมด");

        label2.setBackground(new java.awt.Color(255, 255, 255));
        label2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        label2.setText("0");

        javax.swing.GroupLayout available_p1Layout = new javax.swing.GroupLayout(available_p1);
        available_p1.setLayout(available_p1Layout);
        available_p1Layout.setHorizontalGroup(
            available_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p1Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, available_p1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        available_p1Layout.setVerticalGroup(
            available_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(available_p1Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(75, 75, 75)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(available_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(available_p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(available_p1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(available_p2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnChart.setBackground(new java.awt.Color(255, 255, 204));
        pnChart.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnChartLayout = new javax.swing.GroupLayout(pnChart);
        pnChart.setLayout(pnChartLayout);
        pnChartLayout.setHorizontalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnChartLayout.setVerticalGroup(
            pnChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        btn3DPie.setText("โครงสร้างรายจ่าย");
        btn3DPie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3DPieActionPerformed(evt);
            }
        });

        btnLineChart.setText("Revenue/Expense");
        btnLineChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLineChartActionPerformed(evt);
            }
        });

        jLabel13.setText("เดือน :");

        jLabel14.setText("ปี :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 182, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1032, 1032, 1032))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_month, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(select_year, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(btn3DPie)
                                .addGap(18, 18, 18)
                                .addComponent(btnLineChart)
                                .addGap(62, 62, 62))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(select_year, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(select_month, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel16)))
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3DPie)
                    .addComponent(btnLineChart))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Sale", jPanel8);

        javax.swing.GroupLayout SummaryLayout = new javax.swing.GroupLayout(Summary);
        Summary.setLayout(SummaryLayout);
        SummaryLayout.setHorizontalGroup(
            SummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SummaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SummaryLayout.setVerticalGroup(
            SummaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SummaryLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(jLabel_available, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Summary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_available, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Summary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void available_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_available_pMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_available_pMouseClicked

    private void btn3DPie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3DPie1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3DPie1ActionPerformed

    private void btnLineChart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineChart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLineChart1ActionPerformed

    private void btnBarChart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarChart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBarChart1ActionPerformed

    private void btn3DPieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3DPieActionPerformed
        // create dataset for pie chart
        PieChart();
    }//GEN-LAST:event_btn3DPieActionPerformed

    private void btnLineChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLineChartActionPerformed
        // create line chart
        lineCreate();
    }//GEN-LAST:event_btnLineChartActionPerformed

    private void select_yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_yearActionPerformed
        // TODO add your handling code here:
        lineCreate();
    }//GEN-LAST:event_select_yearActionPerformed

    private void select_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_monthActionPerformed
        // TODO add your handling code here:
        lineCreate();


    }//GEN-LAST:event_select_monthActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        lineCreate();
        //System.out.println(timeString);
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String timeString = formatter.format(new Date());
        int m = Integer.parseInt(timeString.substring(3, 5));
        int y = Integer.parseInt(timeString.substring(6));

        select_month.setSelectedIndex(m - 1);
        if (y < 2500) {
            select_year.setSelectedItem(y + "");
        } else {
            select_year.setSelectedItem((y - 543) + "");
        }

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try {
            // TODO add your handling code here:
            notifi();
        } catch (ParseException ex) {
            Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void lineCreate() {
        // create line chart
        int month = Integer.parseInt(select_month.getSelectedItem().toString().substring(0, 2));
        String year = select_year.getSelectedItem().toString();

        JFreeChart lineChart = ChartFactory.createLineChart3D(
                "Revenue-Expense Chart of " + select_month.getSelectedItem().toString().substring(2),
                "date", "Amount(บาท)",
                createDataset(jtable2_getdata(), dashboard2.getRowCount(), month, year),
                PlotOrientation.VERTICAL,
                true, true, false);
        // set color
        CategoryPlot plot = lineChart.getCategoryPlot();

        LineAndShapeRenderer renderer = new LineAndShapeRenderer();

// sets paint color for each series
        plot.getRenderer().setSeriesPaint(0, Color.GREEN);
        plot.getRenderer().setSeriesPaint(1, Color.RED);

        plot.setBackgroundPaint(Color.YELLOW);

        plot.setOutlinePaint(Color.black);
        plot.setOutlineStroke(new BasicStroke(2.0f));

        plot.setRangeGridlinesVisible(true);
        plot.setRangeGridlinePaint(Color.BLACK);

        plot.setDomainGridlinesVisible(true);
        plot.setDomainGridlinePaint(Color.BLACK);

// sets thickness for series (using strokes)
        renderer.setSeriesStroke(0, new BasicStroke(2.0f));
        renderer.setSeriesStroke(1, new BasicStroke(2.0f));

        //plot.setRenderer(renderer);
        // create chart panel the add it to swing panel in  jframe
        ChartPanel chartPanel = new ChartPanel(lineChart);
        pnChart.removeAll();    // clear panel before add new chart
        pnChart.add(chartPanel, BorderLayout.CENTER);
        pnChart.validate();       // refresh panel to display new chart

        update();
    }

    private void PieChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();

        Object[][] data = jtable2_getdata("");
        int row = dashboard2.getRowCount();
        double[] expense = new double[]{0, 0, 0, 0, 0};

        int select_m = Integer.parseInt(select_month.getSelectedItem().toString().substring(0, 2));
        int select_y = Integer.parseInt(select_year.getSelectedItem().toString());
        for (int i = 0; i < row; i++) {

            int month = Integer.parseInt(data[i][0].toString().substring(3, 5));
            String year_c = data[i][0].toString().substring(6);

            System.out.println(select_m + " " + select_y + " " + month + " " + year_c + " ");

            if (select_m == month && (year_c.equals(select_y + "") || year_c.equals((select_y + 543) + ""))) {
                switch (data[i][3].toString()) {
                    case "ค่าซ่อมบำรุง":
                        expense[0] += Double.parseDouble(data[i][1].toString());
                        break;
                    case "ค่าคอมมิสชั่น":
                        expense[1] += Double.parseDouble(data[i][1].toString());
                        break;
                    case "เงินเดือนพนักงาน":
                        expense[2] += Double.parseDouble(data[i][1].toString());
                        break;
                    case "ชำระหนี้":
                        expense[3] += Double.parseDouble(data[i][1].toString());
                        break;
                    case "อื่นๆ":
                        expense[4] += Double.parseDouble(data[i][1].toString());
                        break;

                    default:;
                }

            }

        }

        dataset.setValue("ค่าซ่อมบำรุง", new Double(expense[0]));
        dataset.setValue("ค่าคอมมิสชั่น", new Double(expense[1]));
        dataset.setValue("เงินเดือนพนักงาน", new Double(expense[2]));
        dataset.setValue("ชำระหนี้", new Double(expense[3]));
        dataset.setValue("อื่นๆ", new Double(expense[4]));
        // create pir chart
        JFreeChart chart = ChartFactory.createPieChart3D(
                "Expense Structure of Month", // chart title
                dataset, // data
                true, // include legend
                true,
                false);
        // set chart properties
        final PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(270);
        plot.setForegroundAlpha(0.60f);
        plot.setInteriorGap(0.02);
        plot.setBackgroundPaint(Color.PINK);

        plot.setOutlinePaint(Color.black);
        plot.setOutlineStroke(new BasicStroke(2.0f));

        // create chart panel the add it to swing panel in  jframe
        ChartPanel chartPanel = new ChartPanel(chart);
        pnChart.removeAll();        // clear panel before add new chart
        pnChart.add(chartPanel, BorderLayout.CENTER);
        pnChart.validate();         // refresh panel to display new chart
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        Dash d = new Dash();
        d.setVisible(true);
        Thread t = new Thread(d);
        t.start();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Summary;
    private javax.swing.JPanel Wait;
    private javax.swing.JPanel available_p;
    private javax.swing.JPanel available_p1;
    private javax.swing.JPanel available_p2;
    private javax.swing.JPanel available_p3;
    private javax.swing.JPanel available_p4;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn3DPie;
    private javax.swing.JButton btn3DPie1;
    private javax.swing.JButton btnBarChart1;
    private javax.swing.JButton btnLineChart;
    private javax.swing.JButton btnLineChart1;
    private javax.swing.JPanel busy_p;
    private javax.swing.JTable dashboard;
    private javax.swing.JTable dashboard2;
    private javax.swing.JTable dashboard3;
    private com.toedter.calendar.JCalendar dashcalender;
    private javax.swing.JPanel detail_panel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_a;
    private javax.swing.JPanel jLabel_available;
    private javax.swing.JLabel jLabel_b;
    private javax.swing.JLabel jLabel_c;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label6;
    private javax.swing.JPanel maintainance;
    private javax.swing.JPanel mb_reg;
    private javax.swing.JPanel pnChart;
    private javax.swing.JPanel pnChart1;
    private javax.swing.JPanel rent;
    private javax.swing.JComboBox<String> select_month;
    private javax.swing.JComboBox<String> select_year;
    private javax.swing.JPanel status_panel;
    private javax.swing.JPanel summary_tab;
    private javax.swing.JPanel table_panel;
    private javax.swing.JPanel top_plane;
    private javax.swing.JPanel user_panel;
    // End of variables declaration//GEN-END:variables

    Connection con;
    PreparedStatement pst;

    public void table_update() {
        int c;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://ihost.it.kmitl.ac.th:3306/it61070203_base?useUnicode=true&characterEncoding=utf-8", "it61070203_base", "123456");

            pst = con.prepareStatement("select * from carregis");
            ResultSet Rs = pst.executeQuery();
            ResultSetMetaData rd = Rs.getMetaData();
            c = rd.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) dashboard.getModel();
            df.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(Rs.getString("carid"));
                    v2.add(Rs.getString("carbrand"));
                    v2.add(Rs.getString("carmodel"));
                    v2.add(Rs.getString("carcolor"));
                    v2.add(Rs.getString("cartabian"));
                    v2.add(Rs.getString("carstatus"));
                    v2.add(Rs.getString("date"));

                }
                df.addRow(v2);
            }

            pst = con.prepareStatement("select * from carrepair");
            Rs = pst.executeQuery();
            rd = Rs.getMetaData();
            c = rd.getColumnCount();
            df = (DefaultTableModel) dashboard3.getModel();
            df.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(Rs.getString("carid"));
                    v2.add(Rs.getString("carbrand") + " " + Rs.getString("carmodel") + " " + Rs.getString("carcolor"));
                    v2.add(Rs.getString("cartabian"));
                    v2.add(Rs.getString("type"));
                    v2.add(Rs.getString("about"));
                    v2.add(Rs.getString("daterepair"));
                    v2.add(Rs.getString("dateprb"));
                }
                df.addRow(v2);
            }

            pst = con.prepareStatement("select * from ExpenseTB");
            Rs = pst.executeQuery();
            rd = Rs.getMetaData();
            c = rd.getColumnCount();
            df = (DefaultTableModel) dashboard2.getModel();
            df.setRowCount(0);

            int count = 0;
            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(Rs.getString("date_expense"));
                    v2.add(Rs.getString("type_expense"));
                    v2.add("รายจ่าย");
                    v2.add(Rs.getString("amount_expense"));
                    v2.add("-");

                }
                df.addRow(v2);
                count++;
            }

            pst = con.prepareStatement("select * from Rental");
            Rs = pst.executeQuery();
            rd = Rs.getMetaData();
            c = rd.getColumnCount();
            df = (DefaultTableModel) dashboard2.getModel();
            df.setRowCount(count);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(Rs.getString("due"));
                    v2.add("ให้เช่า " + Rs.getString("car_id"));
                    v2.add("รายรับ");
                    v2.add(Rs.getString("fee"));
                    v2.add(Rs.getString("date"));

                }
                df.addRow(v2);
                count++;
            }

            pst = con.prepareStatement("select * from ReturnCar");
            Rs = pst.executeQuery();
            rd = Rs.getMetaData();
            c = rd.getColumnCount();
            df = (DefaultTableModel) dashboard2.getModel();
            df.setRowCount(count);

            while (Rs.next()) {
                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    v2.add(Rs.getString("Return_Date"));
                    v2.add("ค่าปรับจากรถ " + Rs.getString("ID_Car"));
                    v2.add("รายรับ");
                    v2.add(Rs.getString("Total"));
                    v2.add("-");

                }
                df.addRow(v2);
                count++;
            }

            int r = dashboard.getRowCount(), avai = 0, no_avai = 0;

            int row_check = dashboard3.getRowCount();

            for (int i = 0; i < r; i++) {
                Object obj1 = GetData(dashboard, i, 5);
                if (obj1.equals("ว่าง")) {
                    avai++;
                } else if (obj1.equals("ไม่ว่าง")) {
                    no_avai++;
                }

            }

            jLabel_a.setText(avai + "");
            jLabel_b.setText(no_avai + "");
            jLabel_c.setText(row_check + "");

            dashboard.setAutoCreateRowSorter(true);
            dashboard2.setAutoCreateRowSorter(true);
            dashboard3.setAutoCreateRowSorter(true);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Expense.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Expense.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public Object GetData(JTable table, int row_index, int col_index) {
        return table.getModel().getValueAt(row_index, col_index);
    }

    @Override
    public void run() {

        //jPanel17.add(dt.DigitalWatch());
        //new Dashboard().setVisible(true);
        while (true) {
            SimpleDateFormat formatter = new SimpleDateFormat("dd-MMMM-yyyy HH:mm:ss");
            Date date = new Date();
            String timeString = formatter.format(date);
            jLabel9.setText(timeString);

            try {
                Thread.sleep(10); // interval given in milliseconds
            } catch (InterruptedException ex) {
                Logger.getLogger(Dash.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private double whole_sale;
    private double cost;

    public void update() {
        String month = select_month.getSelectedItem().toString().substring(0, 2);
        int year = Integer.parseInt(select_year.getSelectedItem().toString());

        String[] query = new String[]{month + "-" + year, month + "-" + (year + 543)};
        whole_sale = 0;
        cost = 0;
        setWhole_sale(query);
        label4.setText(whole_sale + "");
        label6.setText(cost + "");
        label2.setText(whole_sale - cost + "");

        if (whole_sale - cost < 0) {
            jLabel17.setText("ขาดทุน");
            label2.setBackground(Color.red);
            jLabel17.setForeground(Color.white);
            available_p1.setBackground(Color.red);
        } else {
            jLabel17.setText("กำไร");
            jLabel17.setForeground(Color.black);
            label2.setBackground(Color.green);
            available_p1.setBackground(Color.green);
        }
        label3.setText(dashboard2.getRowCount() + "");

    }

    public double getWhole_sale() {
        return whole_sale;
    }

    public void setWhole_sale(String[] query) {

        Object[][] data = this.jtable2_getdata();
        for (int i = 0; i < dashboard2.getRowCount(); i++) {
            if (data[i][0].toString().substring(3).equals(query[0]) || data[i][0].toString().substring(3).equals(query[1])) {
                if (data[i][2].equals("รายรับ")) {
                    this.whole_sale += Double.parseDouble(data[i][1].toString());
                }
                if (data[i][2].equals("รายจ่าย")) {
                    this.cost += Double.parseDouble(data[i][1].toString());
                }

            }

        }

    }

    public Object[][] jtable2_getdata() {

        String format_query = select_month.getSelectedItem().toString().substring(0, 2) + "-" + select_year.getSelectedItem().toString();
        int row = dashboard2.getRowCount();
        System.out.println("Query from jTable2 with " + format_query);

        //[date][cost][revenue/expense][detail]
        Object[][] data = new Object[row][4];

        for (int i = 0; i < row; i++) {
            Object date = GetData(dashboard2, i, 0);
            data[i][0] = date.toString();
            double mon = Double.parseDouble(GetData(dashboard2, i, 3).toString());
            data[i][1] = mon;
            data[i][2] = GetData(dashboard2, i, 2).toString();
            data[i][3] = GetData(dashboard2, i, 1).toString();
        }

        return data;
    }

    public Object[][] jtable2_getdata(String n) {

        String format_query = select_month.getSelectedItem().toString().substring(0, 2) + "-" + select_year.getSelectedItem().toString();
        int row = dashboard2.getRowCount();
        System.out.println("Query from jTable2 with " + format_query);

        //[date][cost][revenue/expense][detail]
        Object[][] data = new Object[row][4];

        for (int i = 0; i < row; i++) {
            Object date = GetData(dashboard2, i, 0);
            data[i][0] = date.toString();
            double mon = Double.parseDouble(GetData(dashboard2, i, 3).toString());
            data[i][1] = mon;
            data[i][2] = GetData(dashboard2, i, 2).toString();
            data[i][3] = GetData(dashboard2, i, 1).toString();

        }

        return data;
    }

    public Object[][] jtable2_noti() {
        int row = dashboard.getRowCount();
        System.out.println("Query from jTable1");

        //[date][cost][revenue/expense][detail]
        Object[][] data = new Object[row][5];

        for (int i = 0; i < row; i++) {
            data[i][0] = GetData(dashboard2, i, 0).toString();
            data[i][1] = GetData(dashboard2, i, 1).toString();
            data[i][2] = GetData(dashboard2, i, 2).toString();
            data[i][3] = GetData(dashboard2, i, 3).toString();
            data[i][4] = GetData(dashboard2, i, 4).toString();
        }

        return data;
    }

    private DefaultCategoryDataset createDataset() {
        // same dataset for line chart and bar chart
        String series1 = "รายรับ";
        String series2 = "รายจ่าย";

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        Object[][] spent = new Object[32][2];

        dataset.addValue(15, series1, "JAN");
        dataset.addValue(30, series1, "FEB");
        dataset.addValue(60, series1, "MAR");
        dataset.addValue(120, series1, "APR");
        dataset.addValue(240, series1, "MAY");
        dataset.addValue(300, series1, "JUN");
        dataset.addValue(300, series1, "JUL");
        dataset.addValue(300, series1, "AUG");
        dataset.addValue(300, series1, "SEP");
        dataset.addValue(300, series1, "OCT");
        dataset.addValue(300, series1, "NOV");
        dataset.addValue(300, series1, "DEC");

        dataset.addValue(15, series2, "JAN");
        dataset.addValue(30, series2, "FEB");
        dataset.addValue(60, series2, "MAR");
        dataset.addValue(120, series2, "APR");
        dataset.addValue(240, series2, "MAY");
        dataset.addValue(300, series2, "JUN");
        dataset.addValue(300, series2, "JUL");
        dataset.addValue(300, series2, "AUG");
        dataset.addValue(300, series2, "SEP");
        dataset.addValue(300, series2, "OCT");
        dataset.addValue(300, series2, "NOV");
        dataset.addValue(300, series2, "DEC");

        return dataset;
    }

    private DefaultCategoryDataset createDataset(Object[][] data, int len, int m, String y) {

        String series1 = "รายรับ";
        String series2 = "รายจ่าย";

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        //iวัน
        //spent[i][0] = รายรับ;
        //spent[i][1] = รายจ่าย;
        Object[][] spent = new Object[32][2];

        for (int i = 1; i < (l_month[m - 1]) + 1; i++) {
            double temp_rev = 0, temp_expense = 0;
            for (int j = 0; j < len; j++) {
                int day = Integer.parseInt(data[j][0].toString().substring(0, 2));
                int month = Integer.parseInt(data[j][0].toString().substring(3, 5));
                String year_c = data[j][0].toString().substring(6);

                int year_bd = Integer.parseInt(year_c);

                System.out.println(day + " " + month + " " + year_c + " " + year_bd);
                if ((day == i) && (month == m) && (year_c.equals(y) || (year_bd == Integer.parseInt(y) + 543))) {
                    if (data[j][2].toString().equals("รายรับ")) {
                        temp_rev += Double.parseDouble(data[j][1].toString());
                        System.out.println(data[j][0].toString() + " " + data[j][0].toString().substring(0, 2) + " " + temp_rev);
                    } else {
                        temp_expense += Double.parseDouble(data[j][1].toString());
                        System.out.println(data[j][0].toString() + " " + data[j][0].toString().substring(0, 2) + " " + temp_expense);
                    }
                }

            }
            spent[i][0] = temp_rev;
            spent[i][1] = temp_expense;
        }

        for (int i = 1; i < (l_month[m - 1]) + 1; i++) {
            dataset.addValue(Double.parseDouble(spent[i][0].toString()), series1, i + "");

            dataset.addValue(Double.parseDouble(spent[i][1].toString()), series2, i + "");
        }

        return dataset;
    }

}
